### ISSUE TITLE
checkMsgV3 has been upgraded to two segments of 128 bytes

### ISSUE THREAD

**Issue by xirotech** [irsl/Huawei-Hisuite-KobackupCipherTool#2]
Device: HUAWEI Mate 10
Version: ALP-AL00 10.0.0.156(C00E156R1P4)

Huawei Backup Version: 10.1.1.715
Download Link: https://apkcombo.com/huawei-backup/com.huawei.KoBackup/

Example: 
```
    <column name="checkMsgV3">
      <value String="177a9105e33b3352842d640f91f783231973a62d25149268086eebfaf4039254ecae3a287d68766f40c7d3f15114e2ee38851e733e232f1e543a1937d78836a1_73291f608d91974c4d05914d41db51b1188cfdf9b40cad8fa9ae0ef2dc48f720561fb605e394a019c0c6e939b5316eef1e871c28589579ed9c4facec324b7332"/>
    </column>
```

**Comment by hds1992012011** [comment]
> 设备：华为Mate 10 版本：ALP-AL00 10.0.0.156(C00E156R1P4)
> 
> 华为备份版本：10.1.1.715 下载链接： [https ](https://apkcombo.com/huawei-backup/com.huawei.KoBackup/)
> 
> 例子：
> 
> ```
>     <column name="checkMsgV3">
>       <value String="177a9105e33b3352842d640f91f783231973a62d25149268086eebfaf4039254ecae3a287d68766f40c7d3f15114e2ee38851e733e232f1e543a1937d78836a1_73291f608d91974c4d05914d41db51b1188cfdf9b40cad8fa9ae0ef2dc48f720561fb605e394a019c0c6e939b5316eef1e871c28589579ed9c4facec324b7332"/>
>     </column>
> ```

**Comment by hds1992012011** [comment]
你好，我也遇到了这个问题，有办法解决吗

**Comment by Mao1229** [comment]
> 你好，我也遇到了这个问题，有解决办法吗
同问 您好 请问您解决了吗？

**Comment by xirotech** [comment]
It's a pity that there is still no update after two years. Unfortunately, I don't have a perfect solution, because I haven't paid attention to this problem for 2 years, but in that year I found another project: https://github.com/RealityNet/kobackupdec However, the project has been terminated. Although it solved my problem, its CheckMsgV3 Hash part was not developed, which caused the decryption of the WeChat resource directory to fail, but the decryption of the data directory was successful.


Example: python3 kobackupdec.py -vvv "backup_password" ../backup/2021-11-09_18-35-26-231 ./output


Android WeChat stores data in two directories, one is "data directory" and the other is "resource directory". Among them, only the encrypted chat database is stored in the data directory, and the resource directory stores resources such as pictures, videos, voice files, etc.
